namespace PunjabiMappings {
    const enum Char {
        AdakBindi, //$ਁ GURMUKHI SIGN ADAK BINDI' },
        Bindi,// $ਂ GURMUKHI SIGN BINDI' },
        Visagra,// $ਃ GURMUKHI SIGN VISARGA' },
        //Independent vowels
        Aਅ,// ਅ GURMUKHI LETTER A = aira' },
        Aਆ,// ਆ GURMUKHI LETTER AA' },
        Eਇ,//{ 'Unicode': ['0A07'], 'AnmolLipi':[''], Description: ' ਇ GURMUKHI LETTER I' },
        Eਈ,//{ 'Unicode': ['0A08'], 'AnmolLipi':[''], Description: ' ਈ GURMUKHI LETTER II' },
        Uਉ,//{ 'Unicode': ['0A09'], 'AnmolLipi':[''], Description: ' ਉ GURMUKHI LETTER U' },
        Uਊ,//{ 'Unicode': ['0A0A'], 'AnmolLipi':[''], Description: ' ਊ GURMUKHI LETTER UU' },	
        Eਏ,//{ 'Unicode': ['0A0F'], 'AnmolLipi':[''], Description: ' ਏ GURMUKHI LETTER EE' },
        Aਐ,//{ 'Unicode': ['0A10'], 'AnmolLipi':[''], Description: ' ਐ GURMUKHI LETTER AI' },
        Oਓ,//{ 'Unicode': ['0A13'], 'AnmolLipi':['45'], Description: ' ਓ GURMUKHI LETTER OO' },
        Oਔ,//{ 'Unicode': ['0A14'], Description: ' ਔ GURMUKHI LETTER AU' },
        //Consonants
        Kਕ,//{ 'Unicode': ['0A15'], 'AnmolLipi':['6b'], Description: ' ਕ GURMUKHI LETTER KA' },
        Kਖ,//{ 'Unicode': ['0A16'], 'AnmolLipi':['4b'], Description: ' ਖ GURMUKHI LETTER KHA' },
        Gਗ,//{ 'Unicode': ['0A17'], 'AnmolLipi':['67'], Description: ' ਗ GURMUKHI LETTER GA' },
        Gਘ,//{ 'Unicode': ['0A18'], 'AnmolLipi':['47'], Description: ' ਘ GURMUKHI LETTER GHA' },
        Nਙ,//{ 'Unicode': ['0A19'], 'AnmolLipi':[''], Description: ' ਙ GURMUKHI LETTER NGA' },
        Cਚ,//{ 'Unicode': ['0A1A'], 'AnmolLipi':['63'], Description: ' ਚ GURMUKHI LETTER CA' },
        Cਛ,//{ 'Unicode': ['0A1B'], 'AnmolLipi':['43'], Description: ' ਛ GURMUKHI LETTER CHA' },
        Jਜ,//{ 'Unicode': ['0A1C'], 'AnmolLipi':['6a'], Description: ' ਜ GURMUKHI LETTER JA' },
        Jਝ,//{ 'Unicode': ['0A1D'], 'AnmolLipi':['4a'], Description: ' ਝ GURMUKHI LETTER JHA' },
        Nਞ,//{ 'Unicode': ['0A1E'], 'AnmolLipi':[''], Description: ' ਞ GURMUKHI LETTER NYA' },
        Tਟ,//{ 'Unicode': ['0A1F'], 'AnmolLipi':['74'], Description: ' ਟ GURMUKHI LETTER TTA' },
        Tਠ,//{ 'Unicode': ['0A20'], 'AnmolLipi':['54'], Description: ' ਠ GURMUKHI LETTER TTHA' },
        Dਡ,//{ 'Unicode': ['0A21'], 'AnmolLipi':['66'], Description: ' ਡ GURMUKHI LETTER DDA' },
        Dਢ,//{ 'Unicode': ['0A22'], 'AnmolLipi':['46'], Description: ' ਢ GURMUKHI LETTER DDHA' },
        Nਣ,//{ 'Unicode': ['0A23'], 'AnmolLipi':['78'], Description: ' ਣ GURMUKHI LETTER NNA' },
        Tਤ,//{ 'Unicode': ['0A24'], 'AnmolLipi':['71'], Description: ' ਤ GURMUKHI LETTER TA' },
        Tਥ,//{ 'Unicode': ['0A25'], 'AnmolLipi':['51'], Description: ' ਥ GURMUKHI LETTER THA' },
        Dਦ,//{ 'Unicode': ['0A26'], 'AnmolLipi':['64'], Description: ' ਦ GURMUKHI LETTER DA' },
        Dਧ,//{ 'Unicode': ['0A27'], 'AnmolLipi':['44'], Description: ' ਧ GURMUKHI LETTER DHA' },
        Nਨ,//{ 'Unicode': ['0A28'], 'AnmolLipi':['6e'], Description: ' ਨ GURMUKHI LETTER NA' },
	
        Pਪ,//{ 'Unicode': ['0A2A'], 'AnmolLipi':['70'], Description: ' ਪ GURMUKHI LETTER PA' },
        Fਫ,//{ 'Unicode': ['0A2B'], 'AnmolLipi':['50'], Description: ' ਫ GURMUKHI LETTER PHA' },
        Bਬ,//{ 'Unicode': ['0A2C'], 'AnmolLipi':['62'], Description: ' ਬ GURMUKHI LETTER BA' },
        Bਭ,//{ 'Unicode': ['0A2D'], 'AnmolLipi':['42'], Description: ' ਭ GURMUKHI LETTER BHA' },
        Mਮ,//{ 'Unicode': ['0A2E'], 'AnmolLipi':['6d'], Description: ' ਮ GURMUKHI LETTER MA' },
        Yਯ,//{ 'Unicode': ['0A2F'], 'AnmolLipi':[''], Description: ' ਯ GURMUKHI LETTER YA' },
        Rਰ,//{ 'Unicode': ['0A30'], 'AnmolLipi':['72'], Description: ' ਰ GURMUKHI LETTER RA' },
        Lਲ,//{ 'Unicode': ['0A32'], 'AnmolLipi':['6c'], Description: ' ਲ GURMUKHI LETTER LA' },
        LPairiBindiਲ਼,//  { 'Unicode': ['0A33'], 'AnmolLipi':['4c'], Description: ' ਲ਼ GURMUKHI LETTER LLA' },
        Vਵ,//{ 'Unicode': ['0A35'], 'AnmolLipi':['76'], Description: ' ਵ GURMUKHI LETTER VA' },
        SPairiBindiਸ਼,// { 'Unicode': ['0A36'], 'AnmolLipi':['53'], Description: ' ਸ਼ GURMUKHI LETTER SHA' },
  
        Sਸ,//{ 'Unicode': ['0A38'], 'AnmolLipi':['73'], Description: ' ਸ GURMUKHI LETTER SA' },
        Hਹ,//{ 'Unicode': ['0A39'], 'AnmolLipi':['68'], Description: ' ਹ GURMUKHI LETTER HA' },
        //Various signs
        PairiBindi,//{ 'Unicode': ['0A3C'], 'AnmolLipi':[''], Description: ' $਼ GURMUKHI SIGN NUKTA = pairin bindi' }, 

        // for extending the alphabet to new letters
        //Dependent vowel signs
        Kana,//{ 'Unicode': ['0A3E'], 'AnmolLipi':['77'], Description: ' $ਾ GURMUKHI VOWEL SIGN AA = kanna' },
        Sihari,//{ 'Unicode': ['0A3F'], 'AnmolLipi':['69'], Description: ' $ਿ GURMUKHI VOWEL SIGN I= sihari' },
        // stands to the left of the consonant
        Bihari,//{ 'Unicode': ['0A40'], 'AnmolLipi':['49'], Description: ' $ੀ GURMUKHI VOWEL SIGN II= bihari' },
        Aunkar,//{ 'Unicode': ['0A41'], 'AnmolLipi':['75'], Description: ' $ੁ GURMUKHI VOWEL SIGN U = aunkar' },
        Dulainkar,//{ 'Unicode': ['0A42'], 'AnmolLipi':['55'], Description: ' $ੂ GURMUKHI VOWEL SIGN UU= dulainkar' },
        Lavan,//{ 'Unicode': ['0A47'], 'AnmolLipi':['79'], Description: ' $ੇ GURMUKHI VOWEL SIGN EE= lanvan' },
        Dulavan,//{ 'Unicode': ['0A48'], 'AnmolLipi':['59'], Description: ' $ੈ GURMUKHI VOWEL SIGN AI= dulanvan' },
        Hora,//{ 'Unicode': ['0A4B'], 'AnmolLipi':['6f'], Description: ' $ੋ GURMUKHI VOWEL SIGN OO= hora' },
        Kanaura,//{ 'Unicode': ['0A4C'], 'AnmolLipi':['4f'], Description: ' $ੌ GURMUKHI VOWEL SIGN AU= kanaura' },
        //Virama
        Virama,//{ 'Unicode': ['0A4D'], 'AnmolLipi':[''], Description: ' $੍ GURMUKHI SIGN VIRAMA' },
        PairiRara,//{ 'Unicode': ['0A4D a30'], 'AnmolLipi':['52'], Description: ' pair wich rara' },
        //Sign
        Udaat,//{ 'Unicode': ['0A51'], 'AnmolLipi':[''], Description: ' $ੑ GURMUKHI SIGN UDAAT' }, // todo: confirm
        //Additional consonants
        KPairiBindiਖ਼,//{ 'Unicode': ['0A59'], 'AnmolLipi':[''], Description: ' ਖ਼ GURMUKHI LETTER KHHA≡ 0A16 ਖ  0A3C $਼' },
        GPairiBindiਗ਼,//{ 'Unicode': ['0A5A'], 'AnmolLipi':[''], Description: ' ਗ਼ GURMUKHI LETTER GHHA≡ 0A17 ਗ  0A3C $਼' },
        JPairiBindiਜ਼,//{ 'Unicode': ['0A5B'], 'AnmolLipi':['7a'], Description: ' ਜ਼ GURMUKHI LETTER ZA≡ 0A1C ਜ  0A3C $਼' },
        Rੜ,//{ 'Unicode': ['0A5C'], 'AnmolLipi':['56'], Description: ' ੜ GURMUKHI LETTER RRA' },
        FPairiBindiਫ਼,//{ 'Unicode': ['0A5E'], 'AnmolLipi':[''], Description: ' ਫ਼ GURMUKHI LETTER FA≡ 0A2B ਫ  0A3C $਼' },
        //Reserved For viram punctuation, use the generic Indic 0964 and 0965.
        Danda,//{ 'Unicode': ['0A64'], Description: ' " <reserved> → 0964 ।  devanagari danda' },
        //{ 'Unicode': ['0964'], 'AnmolLipi':['5b'], Description: ' " ।  devanagari danda' },
        DoubleDanda,//{ 'Unicode': ['0A65'], Description: ' " <reserved> → 0965 ॥  devanagari double danda' },
    
        //Digits
        Zero,//{ 'Unicode': ['0A66'], 'AnmolLipi':['30'], Description: ' ੦ GURMUKHI DIGIT ZERO' },
        One,//{ 'Unicode': ['0A67'], 'AnmolLipi':['31'], Description: ' ੧ GURMUKHI DIGIT ONE' },
        Two,//{ 'Unicode': ['0A68'], 'AnmolLipi':['32'], Description: ' ੨ GURMUKHI DIGIT TWO' },
        Three,//{ 'Unicode': ['0A69'], 'AnmolLipi':['33'], Description: ' ੩ GURMUKHI DIGIT THREE' },
        Four,//{ 'Unicode': ['0A6A'], 'AnmolLipi':['34'], Description: ' ੪ GURMUKHI DIGIT FOUR' },
        Five,//{ 'Unicode': ['0A6B'], 'AnmolLipi':['35'], Description: ' ੫ GURMUKHI DIGIT FIVE' },

        Six,//{ 'Unicode': ['0A6C'], 'AnmolLipi':['36'], Description: ' ੬ GURMUKHI DIGIT SIX' },
        Seven,//{ 'Unicode': ['0A6D'], 'AnmolLipi':['37'], Description: ' ੭ GURMUKHI DIGIT SEVEN' },
        Eight,//{ 'Unicode': ['0A6E'], 'AnmolLipi':['38'], Description: ' ੮ GURMUKHI DIGIT EIGHT' },
        Nine,//{ 'Unicode': ['0A6F'], 'AnmolLipi':['39'], Description: ' ੯ GURMUKHI DIGIT NINE' },
        //Gurmukhi-specific additions
        Tippi,//{ 'Unicode': ['0A70'], 'AnmolLipi':['4d'], Description: ' $ੰ GURMUKHI TIPPI • nasalization' },
        Addak,//{ 'Unicode': ['0A71'], 'AnmolLipi':['60'], Description: ' $ੱ GURMUKHI ADDAK • doubles following consonant' },
        Eੲ,//{ 'Unicode': ['0A72'], 'AnmolLipi':['65'], Description: ' ੲ GURMUKHI IRI • base for vowels' },
        Uੳ,//{ 'Unicode': ['0A73'], 'AnmolLipi':['61'], Description: ' ੳ GURMUKHI URA • base for vowels' },
        Aੴ,//{ 'Unicode': ['0A74'], 'AnmolLipi':['3c 3e', '3c'], Description: ' ੴ GURMUKHI EK ONKAR • God is One' },
        Yakash,//{ 'Unicode': ['0A75'], 'AnmolLipi':[''], Description: ' $ੵ GURMUKHI SIGN YAKASH' },    
    
        //Anmol Lipi Specific
        KanaBindi,//{ 'Unicode': ['0A3E 0A02'], 'AnmolLipi':['57'], Description: ' kana ate bindi' },
        PairiHaha,//{ 'Unicode': ['a4d a39'], 'AnmolLipi':['48'], Description: ' pair wich haha' }      
    
    }

    export let compositions: { [key: number]: number[] } = {
        [Char.AdakBindi]: [Char.Addak, Char.Bindi],
        [Char.Aਆ]: [Char.Aਅ, Char.Kana],
        [Char.Eਇ]: [Char.Sihari, Char.Eੲ],
        [Char.Eਈ]: [Char.Eੲ, Char.Bihari],
        [Char.Uਉ]: [Char.Uੳ, Char.Aunkar],
        [Char.Uਊ]: [Char.Uੳ, Char.Dulainkar],
        [Char.Eਏ]: [Char.Eੲ, Char.Lavan],
        [Char.Aਐ]: [Char.Aਅ, Char.Dulavan],
        //[CharDef.Oਓ]: ,
        [Char.Oਔ]: [Char.Aਅ, Char.Aunkar],
        [Char.LPairiBindiਲ਼]: [Char.Lਲ, Char.PairiBindi],
        [Char.SPairiBindiਸ਼]: [Char.Sਸ, Char.PairiBindi],
        [Char.KPairiBindiਖ਼]: [Char.Kਖ, Char.PairiBindi],
        [Char.GPairiBindiਗ਼]: [Char.Gਗ, Char.PairiBindi],
        [Char.JPairiBindiਜ਼]: [Char.Jਜ, Char.PairiBindi],
        [Char.FPairiBindiਫ਼]: [Char.Fਫ, Char.PairiBindi],
        [Char.DoubleDanda]: [Char.Danda, Char.Danda],
        [Char.KanaBindi]: [Char.Kana, Char.Bindi],
        [Char.PairiHaha]: [Char.Virama, Char.Hਹ],
        [Char.PairiRara]: [Char.Virama, Char.Rਰ],
    };

    let unicodeFont = {
        moveRightCharacters: [Char.Sihari],
        characterCodes: makeArray({
            [Char.AdakBindi]: 0x0A01,
            [Char.Bindi]: 0x0A02,
            [Char.Visagra]: 0x0A03,
            [Char.Aਅ]: 0x0A05,
            [Char.Aਆ]: 0x0A06,
            [Char.Eਇ]: 0x0A07,
            [Char.Eਈ]: 0x0A08,
            [Char.Uਉ]: 0x0A09,
            [Char.Uਊ]: 0x0A0A,
            [Char.Eਏ]: 0x0A0F,
            [Char.Aਐ]: 0x0A10,
            [Char.Oਓ]: 0x0A13,
            [Char.Oਔ]: 0x0A14,
            [Char.Kਕ]: 0x0A15,
            [Char.Kਖ]: 0x0A16,
            [Char.Gਗ]: 0x0A17,
            [Char.Gਘ]: 0x0A18,
            [Char.Nਙ]: 0x0A19,
            [Char.Cਚ]: 0x0A1A,
            [Char.Cਛ]: 0x0A1B,
            [Char.Jਜ]: 0x0A1C,
            [Char.Jਝ]: 0x0A1D,
            [Char.Nਞ]: 0x0A1E,
            [Char.Tਟ]: 0x0A1F,
            [Char.Tਠ]: 0x0A20,
            [Char.Dਡ]: 0x0A21,
            [Char.Dਢ]: 0x0A22,
            [Char.Nਣ]: 0x0A23,
            [Char.Tਤ]: 0x0A24,
            [Char.Tਥ]: 0x0A25,
            [Char.Dਦ]: 0x0A26,
            [Char.Dਧ]: 0x0A27,
            [Char.Nਨ]: 0x0A28,
            [Char.Pਪ]: 0x0A2A,
            [Char.Fਫ]: 0x0A2B,
            [Char.Bਬ]: 0x0A2C,
            [Char.Bਭ]: 0x0A2D,
            [Char.Mਮ]: 0x0A2E,
            [Char.Yਯ]: 0x0A2F,
            [Char.Rਰ]: 0x0A30,
            [Char.Lਲ]: 0x0A32,
            [Char.LPairiBindiਲ਼]: 0x0A33,
            [Char.Vਵ]: 0x0A35,
            [Char.SPairiBindiਸ਼]: 0x0A36,
            [Char.Sਸ]: 0x0A38,
            [Char.Hਹ]: 0x0A39,
            [Char.PairiBindi]: 0x0A3C,
            [Char.Kana]: 0x0A3E,
            [Char.Sihari]: 0x0A3F,
            [Char.Bihari]: 0x0A40,
            [Char.Aunkar]: 0x0A41,
            [Char.Dulainkar]: 0x0A42,
            [Char.Lavan]: 0x0A47,
            [Char.Dulavan]: 0x0A48,
            [Char.Hora]: 0x0A4B,
            [Char.Kanaura]: 0x0A4C,
            [Char.Virama]: 0x0A4D,
            [Char.Udaat]: 0x0A51,
            [Char.KPairiBindiਖ਼]: 0x0A59,
            [Char.GPairiBindiਗ਼]: 0x0A5A,
            [Char.JPairiBindiਜ਼]: 0x0A5B,
            [Char.Rੜ]: 0x0A5C,
            [Char.FPairiBindiਫ਼]: 0x0A5E,
            [Char.Danda]: 0x0964,
            [Char.DoubleDanda]: 0x0965,
            [Char.Zero]: 0x0A66,
            [Char.One]: 0x0A67,
            [Char.Two]: 0x0A68,
            [Char.Three]: 0x0A69,
            [Char.Four]: 0x0A6A,
            [Char.Five]: 0x0A6B,
            [Char.Six]: 0x0A6C,
            [Char.Seven]: 0x0A6D,
            [Char.Eight]: 0x0A6E,
            [Char.Nine]: 0x0A6F,
            [Char.Tippi]: 0x0A70,
            [Char.Addak]: 0x0A71,
            [Char.Eੲ]: 0x0A72,
            [Char.Uੳ]: 0x0A73,
            [Char.Aੴ]: 0x0A74,
            [Char.Yakash]: 0x0A75
        })
    };

    let anmolFont = {
        moveRightCharacters: [],
        characterCodes: makeArray({
            [Char.AdakBindi]: 0x0A01,
            [Char.Bindi]: 0x4e,
            [Char.Aਅ]: 0x41,
            [Char.Oਓ]: 0x45,
            [Char.Kਕ]: 0x6b,
            [Char.Kਖ]: 0x4b,
            [Char.Gਗ]: 0x67,
            [Char.Gਘ]: 0x47,
            //[Char.Nਙ]:   ,
            [Char.Cਚ]: 0x63,
            [Char.Cਛ]: 0x43,
            [Char.Jਜ]: 0x6a,
            [Char.Jਝ]: 0x4a,
            //[Char.Nਞ]:  0x ,
            [Char.Tਟ]: 0x74,
            [Char.Tਠ]: 0x54,
            [Char.Dਡ]: 0x66,
            [Char.Dਢ]: 0x46,
            [Char.Nਣ]: 0x78,
            [Char.Tਤ]: 0x71,
            [Char.Tਥ]: 0x51,
            [Char.Dਦ]: 0x64,
            [Char.Dਧ]: 0x44,
            [Char.Nਨ]: 0x6e,
            [Char.Pਪ]: 0x70,
            [Char.Fਫ]: 0x50,
            [Char.Bਬ]: 0x62,
            [Char.Bਭ]: 0x42,
            [Char.Mਮ]: 0x6d,
            //[Char.Yਯ]:   ,
            [Char.Rਰ]: 0x72,
            [Char.Lਲ]: 0x6c,
            [Char.LPairiBindiਲ਼]: 0x4c,
            [Char.Vਵ]: 0x76,
            [Char.SPairiBindiਸ਼]: 0x53,
            [Char.Sਸ]: 0x73,
            [Char.Hਹ]: 0x68,
            [Char.PairiBindi]: 0x01,
            [Char.Kana]: 0x77,
            [Char.Sihari]: 0x69,
            [Char.Bihari]: 0x49,
            [Char.Aunkar]: 0x75,
            [Char.Dulainkar]: 0x55,
            [Char.Lavan]: 0x79,
            [Char.Dulavan]: 0x59,
            [Char.Hora]: 0x6f,
            [Char.Kanaura]: 0x4f,
            [Char.PairiRara]:0x52,
            [Char.JPairiBindiਜ਼]: 0x7a,
            [Char.Rੜ]: 0x56,
            [Char.Danda]: 0x5b,
            //[Char.DoubleDanda]:  0x0965 , //  'Description' " <reserved> → 0965 ॥  devanagari double danda' ,
            [Char.Zero]: 0x30,
            [Char.One]: 0x31,
            [Char.Two]: 0x32,
            [Char.Three]: 0x33,
            [Char.Four]: 0x34,
            [Char.Five]: 0x35,
            [Char.Six]: 0x36,
            [Char.Seven]: 0x37,
            [Char.Eight]: 0x38,
            [Char.Nine]: 0x39,
            [Char.Tippi]: 0x4d,
            [Char.Addak]: 0x60,
            [Char.Eੲ]: 0x65,
            [Char.Uੳ]: 0x61,        
            [Char.KanaBindi]: 0x57,
            [Char.PairiHaha]: 0x48
            //[Char.Aੴ]:  0x0A74 , //  'AnmolLipi':['3c 3e', '3c'], Description: ' ੴ GURMUKHI EK ONKAR • God is One' ,
        })
    }


    function makeArray<T>(...configs: { [key: number]: T }[]) {
        var c: T[] = [];

        for (let a of configs) {
            for (var x in a) {
                if (a.hasOwnProperty(x)) {
                    c[x] = a[x];
                }
            }
        }
        return c;
    }


    export let fontConvertorConfigs = {
        "Unicode": unicodeFont,
        "AnmolLipi": anmolFont
    };
}
